### ISSUE TITLE
Inkporter issues. 

### ISSUE THREAD

**Issue by JustsayTanzania** [raniaamina/inkporter#10]
I have installed the Inkporter to my extensions but displays an error and doesn't function. I am using inkscape 1.0 and Inkporter 1.0.

**Comment by maslanangdev** [comment]
the problem is you're not input the ID Pattern yet, give your objects an unique pattern for their ID and put that unique pattern on ID Pattern input box

check this post for more details
https://www.facebook.com/groups/286080284852022/permalink/2794543784005647/?comment_id=2795875983872427&reply_comment_id=2816733015120057
